---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Katya Shepherd Johnson"
pagetitle: "L01 Katya Shepherd Johnson"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Katya's Github Repo](https://github.com/stat301-3-2026-spring/l01-review-kshepjohn.git)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning has a target variable that is being predicted by other variables. You are using a function of dependent variables to get the patterns of an external variable. 

Unsupervised learning is used to learn the patterns in a variable. There is no prediction occurring, instead it is more like clustering. 

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

First, you break the data into a training set and a testing set. Say that there are 5 folds. You would shuffle the rows randomly or stratified randomly. Next, you would break this shuffled data into 5 groups. For the first iteration, four of the groups would become the analysis set that is used to train the model, and then this trained model would be tested with the remaining one group (the assessment set). The resulting metrics such as the RMSE are then taken from the predictions on the assessment set. The process used for this iteration would then be repeated so that each of the 5 groups are used as the assessment set one time. If there are repeats, then you would repeat the above process using the training set. This gives many different estimates of the RMSE that can be averaged to estimate what a possible value would be for the test RMSE. 

We use it because...



:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

